### ISSUE TITLE
[FEATURE] shadow_mode support

### ISSUE THREAD

**Issue by deferraz** [zufardhiyaulhaq/istio-ratelimit-operator#18]
Any ideas or possibilities in the roadmap to support the latest release of ratelimit by the original repository of envoy proxy? Nowadays the HEAD git repository has the support of [shadow_mode](https://github.com/envoyproxy/ratelimit#shadowmode), this could be handy to include the ratelimit rules but without enforcing, only checking if the ratelimit will be aggressive, generate some kind of impact in the production environment
If there is some kind of possible test that I could do, I would be glad to help

**Comment by zufardhiyaulhaq** [comment]
Hi @deferraz currently you can enable shadow_mode https://github.com/zufardhiyaulhaq/istio-ratelimit-operator/pull/23 in GlobalRateLimit object. please check the master branch
