### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by WagnerCarvalho** [zufardhiyaulhaq/istio-ratelimit-operator#31]
**Is your feature request related to a problem? Please describe.**
Please, could you add documentation about sidecar?

**Describe the solution you'd like**
simple example of what a sidecar documentation

**Describe alternatives you've considered**
My doubt is how do I add the inject-sidecar to the YAML of my POD? Is there any annotation?

**Comment by zufardhiyaulhaq** [comment]
Hi @WagnerCarvalho sorry, I think it's already define here, https://github.com/zufardhiyaulhaq/istio-ratelimit-operator/blob/master/examples/local/README.md

**Comment by zufardhiyaulhaq** [comment]
did you want to implement global ratelimit or local ratelimit?
